export const difficulties = {
  beginner: {
    width: 9,
    height: 9,
    numMines: 10,
    showTimer: true,
    safeFirstClick: false,
    revealContiguousNumbers: false,
    autoRestart: false,
    timeLimit: 0,
  },
  intermediate: {
    width: 16,
    height: 16,
    numMines: 40,
    showTimer: true,
    safeFirstClick: false,
    revealContiguousNumbers: false,
    autoRestart: false,
    timeLimit: 0,
  },
  expert: {
    width: 30,
    height: 16,
    numMines: 99,
    showTimer: true,
    safeFirstClick: false,
    revealContiguousNumbers: false,
    autoRestart: false,
    timeLimit: 0,
  },
};
